name: zen

description: my personal OS image focused on a clean and minimal dev and general use setup

base-image: quay.io/fedora-ostree-desktops/sway-atomic

image-version: 43

modules:
  - from-file: common/sddm-modules.yml
  - from-file: common/common-modules.yml
  - from-file: common/gaming-modules.yml
  - from-file: common/sway-modules.yml
  - from-file: common/final-modules.yml

  - type: signing
